src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SongRepository::class)]
class Song
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'songs')]
    private ?Author $author = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'songs')]
    private ?Album $album = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_path = null;

    #[ORM\ManyToOne(inversedBy: 'songs')]
    private ?Categorie $categorie = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): static
    {
        $this->album = $album;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(?string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/SongType.php
<?php

namespace App\Form;

use App\Entity\Album;
use App\Entity\Author;
use App\Entity\Categorie;
use App\Entity\Song;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class SongType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
            ->add('image_path', FileType::class, [
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using attributes
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '10240k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Picture',
                    ]),
                ]])
            ->add('author', EntityType::class, [
                'class' => Author::class,
                'choice_label' => 'name',
            ])
            ->add('album', EntityType::class, [
                'class' => Album::class,
                'choice_label' => 'name',
            ])
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Song::class,
        ]);
    }
}

src/Form/SongsType.php
<?php

namespace App\Form;

use App\Entity\Songs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class SongsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('author')
            ->add('album')
            ->add('year')
            ->add('categorie')
            ->add('image_path', FileType::class, [
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using attributes
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '10240k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Picture',
                    ])
                ]])
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Songs::class,
        ]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\Song;
use App\Form\SongType;
use App\Repository\AuthorRepository;
use App\Repository\CategorieRepository;
use App\Repository\SongRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/song')]
class SongController extends AbstractController
{

    #[Route('/', name: 'app_song_index', methods: ['GET'])]
    public function index(SongRepository $songRepository, CategorieRepository $categoryRepository, Request $request, TokenStorageInterface $tokenStorage, AuthorRepository $authorRepository): Response
    {
        $token = $tokenStorage->getToken();
        if (!$token || !$token->getUser()) {
            flash()->addError('You need to be logged in to access this resource');
            return $this->redirectToRoute('app_login');
        }

        $this->denyAccessUnlessGranted('ROLE_USER');

        // Récupérer toutes les catégories
        $categories = $categoryRepository->findAll();
        $authors = $authorRepository->findAll();
        $author = null;
        $category = null;

        // Initialiser la variable $songs avec toutes les chansons
        $songs = $songRepository->findAll();

        // Vérifier si une catégorie a été sélectionnée via l'URL
        $categoryId = $request->query->get('category');
        if ($categoryId) {
            // Récupérer la catégorie sélectionnée
            $category = $categoryRepository->find($categoryId);

            // Filtrer les chansons par catégorie
            $songs = $songRepository->findBy(['categorie' => $category]);

            // Récupérer le nom de la catégorie sélectionnée
            $categoryName = $category->getName();

            // Définir un flash message avec le nom de la catégorie sélectionnée
        flash()->addInfo('Getting all the songs form '.$categoryName.' category');
        }

        $authorId = $request->query->get('author');
        if ($authorId) {
            $author = $authorRepository->find($authorId);

            // Filtrer les chansons par auteur
            $songs = $songRepository->findBy(['author' => $author]);

            $authorName = $author->getName();
            flash()->addInfo('Getting all the songs form the author '.$authorName);

        }

        return $this->render('song/index.html.twig', [
            'songs' => $songs,
            'authors' => $authors,
            'author' => $author,
            'categories' => $categories,
            'category' => $category,
        ]);
    }

    #[Route('/new', name: 'app_song_new', methods: ['GET', 'POST'])]
    public function new (Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger, TokenStorageInterface $tokenStorage): Response
    {
        $token = $tokenStorage->getToken();
        if (!$token || !$token->getUser()) {
            flash()->addError('You need to be logged in to access this resource');
            return $this->redirectToRoute('app_login');
        }

        $this->denyAccessUnlessGranted('ROLE_USER');

        $song = new Song();
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image_path')->getData();

            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('image_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $song->setImagePath($newFilename);
            }

            $entityManager->persist($song);
            $entityManager->flush();
            flash()->addSuccess("Song added successfully");
            return $this->redirectToRoute('app_song_index', [], Response::HTTP_SEE_OTHER);
        }
        $token = $tokenStorage->getToken();
        if (!$token || !$token->getUser()) {
            flash()->addError('You need to be logged in to access this resource');
            return $this->redirectToRoute('app_login');
        }

        $this->denyAccessUnlessGranted('ROLE_USER');

        return $this->render('song/new.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_song_show', methods: ['GET'])]
    public function show(Song $song): Response
    {
        return $this->render('song/show.html.twig', [
            'song' => $song,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_song_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Song $song, EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage): Response
    {
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_song_index', [], Response::HTTP_SEE_OTHER);
        }
        $token = $tokenStorage->getToken();
        if (!$token || !$token->getUser()) {
            flash()->addError('You need to be logged in to access this resource');
            return $this->redirectToRoute('app_login');
        }

        $this->denyAccessUnlessGranted('ROLE_USER');

        return $this->render('song/edit.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_song_delete', methods: ['POST'])]
    public function delete(Request $request, Song $song, EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage): Response
    {
        if ($this->isCsrfTokenValid('delete' . $song->getId(), $request->request->get('_token'))) {
            $entityManager->remove($song);
            $entityManager->flush();
        }
        $token = $tokenStorage->getToken();
        if (!$token || !$token->getUser()) {
            $this->addFlash('error', 'You need to be logged in to access this resource');
            return $this->redirectToRoute('app_login');
        }

        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->redirectToRoute('app_song_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/SongsController.php
<?php

namespace App\Controller;

use App\Entity\Songs;
use App\Form\SongsType;
use App\Repository\SongsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/songs')]
class SongsController extends AbstractController
{
    #[Route('/', name: 'app_songs_index', methods: ['GET'])]
    public function index(SongsRepository $songsRepository): Response
    {
        flash()->addInfo("Retriving all the songs");
        return $this->render('songs/index.html.twig', [
            'songs' => $songsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_songs_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $song = new Songs();
        $form = $this->createForm(SongsType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form-> get('image_path')->getData();

            if($imageFile){
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

            
            try {
                $imageFile->move(
                    $this->getParameter('image_directory'),
                    $newFilename
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $song->setImagePath($newFilename);
        }

            $entityManager->persist($song);
            $entityManager->flush();
            flash()->addSuccess("Song added successfully");
            return $this->redirectToRoute('app_songs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('songs/new.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_songs_show', methods: ['GET'])]
    public function show(Songs $song): Response
    {
        return $this->render('songs/show.html.twig', [
            'song' => $song,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_songs_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Songs $song, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SongsType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            flash()->addWarning("Song edited successfully");

            return $this->redirectToRoute('app_songs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('songs/edit.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_songs_delete', methods: ['POST'])]
    public function delete(Request $request, Songs $song, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$song->getId(), $request->request->get('_token'))) {
            $entityManager->remove($song);
            $entityManager->flush();
        }
        flash()->addError("Song deleted successfully");

        return $this->redirectToRoute('app_songs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/song/_delete_form.html.twig
<div class="container">
  <div class="d-flex align-items-center justify-content-center h-100">
<form method="post" action="{{ path('app_song_delete', {'id': song.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ song.id) }}">
    <button class="btn">Delete</button>
</form>
  </div>
</div>

templates/song/_form.html.twig
<div class="container">
  <div class="d-flex align-items-center justify-content-center h-100">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
  </div>
</div>

templates/song/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Song{% endblock %}

{% block stylesheets %}
	{{ encore_entry_link_tags('form') }}
{% endblock %}
{% block body %}
    <h1>Edit Song</h1>

    {{ include('song/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_song_index') }}">back to list</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}

templates/song/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Song index
{% endblock %}
{% block stylesheets %}
	{{ encore_entry_link_tags('main') }}
{% endblock %}


{% block javascript %}
	{{ encore_entry_script_tags('main') }}
{% endblock %}

{% block body %}


	<nav class="navbar navbar-expand-lg ">
		<div class="container-fluid">
			<div id="div-brand">
				<a class="navbar-brand" href="{{ path('app_song_index') }}"><img src="{{asset('images/logo.png')}}" alt="" id="brand"></a>
			</div>
			<button class="navbar-toggler d-lg-none d-lg-block" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item dropdown" id="drop-add">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Add
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li>
								<a href="{{ path('app_author_new') }}">New Author</a>
							</li>
							<li>
								<a href="{{ path('app_album_new') }}">New Album</a>
							</li>
							<li>
								<a href="{{ path('app_categorie_new') }}">New Category</a>
							</li>
							<li>
								<a href="{{ path('app_song_new') }}">New Song</a>
							</li>
						</ul>
					</li>
				</ul>

				<ul class="navbar-nav">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Author
						</a>

						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li>
								<a class="dropdown-item" href="{{ path('app_song_index') }}">All</a>
							</li>
							{% for author in authors %}
								<li>
									<a class="dropdown-item" href="{{ path('app_song_index') }}?category={{ author.id }}">{{ author.name }}</a>
								</li>
							{% endfor %}
						</ul>
					</li>
				</ul>


				<ul class="navbar-nav">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Category
						</a>

						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li>
								<a class="dropdown-item" href="{{ path('app_song_index') }}">All</a>
							</li>
							{% for category in categories %}
								<li>
									<a class="dropdown-item" href="{{ path('app_song_index') }}?category={{ category.id }}">{{ category.name }}</a>
								</li>
							{% endfor %}
						</ul>
					</li>
				</ul>
				<form class="d-flex">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-light" type="submit">Search</button>
				</form>
				{% if app.user %}
					<div class="d-flex" id="logout">
						<div id="div-username">
							<p>{{ app.user.username }}</p>

						</div>


					</div>
					<div class="nav-item" id="logout">
						<button type="button" class="btn btn-outline-dark">
							<a href="{{ path('app_logout') }}">Logout</a>
						</button>
					</div>
				{% endif %}
			</div>

		</div>
	</nav>


	<div class="container">
		<div class="row">
			{% if category %}
				{% for song in songs %}
					{% if song.categorie.id == category.id %}
						<div class="col-md-3 col-sm-6 mb-4">
							<a href="{{ path('app\_song\_show', {'id': song.id}) }}">
								<div class="card mx-auto" style="width: 18rem;">
									<img class="card-img-top" src="{{ asset('uploads/images/' ~ song.imagePath) }}" alt="Card image cap" style="max-width: 100%; max-height: 200px;">
									<div class="card-body">
										<p class="card-text">{{ song.name }}</p>
										<p class="card-text">{{ song.author.name }}</p>
									</div>
								</div>
							</a>
						</div>
					{% else %}
						<div class="col">
							<p>No records found</p>
						</div>
					{% endif %}
				{% endfor %}
			{% elseif author %}
				<div class="col">
					<p>Showing songs for author "{{ author.name }}"</p>
				</div>
				{% for song in songs %}
					{% if song.author.id == author.id %}
						<div class="col-md-3 col-sm-6 mb-4">
							<a href="{{ path('app\_song\_show', {'id': song.id}) }}">
								<div class="card mx-auto" style="width: 18rem;">
									<img class="card-img-top" src="{{ asset('uploads/images/' ~ song.imagePath) }}" alt="Card image cap" style="max-width: 100%; max-height: 200px;">
									<div class="card-body">
										<p class="card-text">{{ song.name }}</p>
										<p class="card-text">{{ song.author.name }}</p>
									</div>
								</div>
							</a>
						</div>
						{% else %}
					{% endif %}
				{% endfor %}
			{% else %}
				{% for song in songs %}
					<div class="col-md-3 col-sm-6 mb-4">
						<a href="{{ path('app\_song\_show', {'id': song.id}) }}">
							<div class="card mx-auto" style="width: 18rem;">
								<img class="card-img-top" src="{{ asset('uploads/images/' ~ song.imagePath) }}" alt="Card image cap" style="max-width: 100%; max-height: 200px;">
								<div class="card-body">
									<p class="card-text">{{ song.name }}</p>
									<p class="card-text">{{ song.author.name }}</p>
								</div>
							</div>
						</a>
					</div>
				{% else %}
					<div class="col">
						<p>No records found</p>
					</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/song/new.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ encore_entry_link_tags('form') }}
{% endblock %}


{% block title %}New Song{% endblock %}

{% block body %}
    <h1>Create new Song</h1>

    {{ include('song/_form.html.twig') }}

    <a href="{{ path('app_song_index') }}">back to list</a>
{% endblock %}

templates/song/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Song{% endblock %}

{% block stylesheets %}
	{{ encore_entry_link_tags('form') }}
{% endblock %}
{% block body %}
    <h1>Song</h1>
<div class="container"></div>    

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ song.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ song.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ song.content }}</td>
            </tr>
            <tr>
                <th>Image_path</th>
                <td>{{ song.imagePath }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_song_index') }}">back to list</a>

    <a href="{{ path('app_song_edit', {'id': song.id}) }}">edit</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}